### ISSUE TITLE
No CUDA training error

### ISSUE THREAD

**Issue by billychasen** [liuliu/ccv#109]
I'm trying to run training on a mac and tried two different computers, both fail here:

`- at epoch 001 / 100 => going through 1 / 2 for testsAssertion failed: (CCV_GET_CHANNEL((*a)->type) == convnet->channels), function ccv_convnet_encode, file ccv_convnet.c, line 647.
Abort trap: 6`

I'm wondering if you could shed some light on how to fix this.

Thanks

**Comment by billychasen** [comment]
forgot command line

`./image-net --train-list ~/ccv/training/training.txt --test-list ~/ccv/training/test.txt --working-dir ~/ccv/workingdir`

**Comment by billychasen** [comment]
when using CUDA, I now get this assertion.

`Assertion failed: (layers[i].w), function _cwc_convnet_alloc_layers, file cuda/cwc_convnet.cu, line 155`

**Comment by liuliu** [comment]
It would be helpful to provide which GPU version you use (arch and memory), and which version of ccv (git-sha1 or branch). The current unstable have a immature VGG model, which will blow-up close to 6GiB GPU memory. On the other hand, the MattNet model is probably smaller.

cifar-10.c should work with CPU cases, image-net.c doesn't work with CPU implementation at all.

**Comment by billychasen** [comment]
I tried with both stable and unstable branches. It may also be not enough memory. I have an NVIDIA GeForce GT 650M 1024MB.

I'm curious what machine you trained on. I tried an AWS GPU but it was throwing weird errors

**Comment by liuliu** [comment]
The stable can be trained with a 6GiB Titan but will fail on 3GiB GTX.

I trained the AlexNet (in stable) / MattNet with one Titan setup. The VGG model is not going to finish training with one Titan setup, thus, I am working on a 4-Titan setup.

**Comment by billychasen** [comment]
okay thanks, I'll find some beefier GPUs

**Comment by liuliu** [comment]
I am in the process of refactoring that part of the code, so you probably want to work on either stable branch, or unstable at / before 29f76e24a0f89acd9731f0d41b027f7cdcc1f914

I should cut a branch when MattNet is done. With VGG model, current state of fairs is a bit messy.
