### ISSUE TITLE
Make config file not found

### ISSUE THREAD

**Issue by KevinJaspal** [liuliu/ccv#110]
Hi,

I really love this project and would like to give it a spin. I tried building both the master and stable branch and I get the following error when running make inside the lib folder:

make
makefile:1: config.mk: No such file or directory
make: **\* No rule to make target `config.mk'.  Stop.

I noticed there isn't a config.mk file in the folder, however there is a config.mk.in file. This is one of the few times I'm building a C package so I definitely apologize if this is something straightforward I'm doing wrong. 

Thanks,

Kevin

**Comment by liuliu** [comment]
It seems that you need to run ./configure under ./lib to generate config.mk file.

**Comment by KevinJaspal** [comment]
Thanks! That fixed it. If running ./configure could be mentioned in the getting started documentation that would be helpful.
