### ISSUE TITLE
The PCA performed on RGB pixels

### ISSUE THREAD

**Issue by MustangYan** [liuliu/ccv#111]
Can you show me which part of your code implements the Pca on altering the intensity of RGB pixels as introduced in Alex's paper? thank you very much

**Comment by MustangYan** [comment]
As mentioned in your webpage about ccv,you say color augmentation is applied with Gaussian random coefficient sampled with sigma == 0.001,so i want to know how you compute the covariance matrix of RGB pixels in detail and the detailed procedure of the color augmentation... 3Q liuliu...

**Comment by liuliu** [comment]
https://github.com/liuliu/ccv/blob/unstable/lib/cuda/cwc_convnet.cu#L2316
