### ISSUE TITLE
[cnnclassify.c] compile error

### ISSUE THREAD

**Issue by geffy** [liuliu/ccv#113]
Hi!
Cannot compile ./bin/cnnclassify.c.
Revision a569221e40.

gcc cnnclassify.c -o cnnclassify.o -c -O3 -Wall -I"../lib" -msse2 -D HAVE_LIBPNG -D HAVE_LIBJPEG -D HAVE_CBLAS -D HAVE_TESSERACT -D HAVE_AVCODEC -D HAVE_AVFORMAT -D HAVE_SWSCALE -D HAVE_SSE2
cnnclassify.c: In function ‘main’:
cnnclassify.c:50:4: error: variable-sized object may not be initialized
    ccv_dense_matrix_t\* images[BATCH_SIZE] = {
    ^
cnnclassify.c:52:4: warning: excess elements in array initializer [enabled by default]
    };
    ^
cnnclassify.c:52:4: warning: (near initialization for ‘images’) [enabled by default]
cnnclassify.c:72:6: error: variable-sized object may not be initialized
      ccv_array_t\* ranks[BATCH_SIZE] = {
      ^
cnnclassify.c:74:6: warning: excess elements in array initializer [enabled by default]
      };
      ^
cnnclassify.c:74:6: warning: (near initialization for ‘ranks’) [enabled by default]
cnnclassify.c:94:5: error: variable-sized object may not be initialized
     ccv_array_t\* ranks[BATCH_SIZE] = {
     ^
cnnclassify.c:96:5: warning: excess elements in array initializer [enabled by default]
     };
     ^
cnnclassify.c:96:5: warning: (near initialization for ‘ranks’) [enabled by default]
cnnclassify.c:45:9: warning: ignoring return value of ‘chdir’, declared with attribute warn_unused_result [-Wunused-result]
    chdir(argv[3]);
         ^
I will be happy if you fix that =)

**Comment by liuliu** [comment]
fixed in unstable. this problem is not in stable.
