### ISSUE TITLE
LibCCV on ARM

### ISSUE THREAD

**Issue by javierluiso** [liuliu/ccv#115]
Hi, I'm doing research for an alternative library for OpenCV in order to compile and use on ARM platform. My ultimate goal is to use NEON Technology present in Cortex Processors. 
1. Do you know previous experience using CCV on ARM?
2. Is CCV coding using SSE for Intel platform or CUDA?

Thanks

**Comment by guardrex** [comment]
I don't know if it helps, but I worked out CCV issues for Raspberry Pi (being ARM-based) at: https://github.com/liuliu/ccv/issues/75

**Comment by liuliu** [comment]
1). Yes: http://ci.libccv.org/builders/arm-runtests

2). A few parts accelerated with SSE / NEON, the convolutional network part is for example, the convnet also has CUDA implementation, others are not, but still "performant" in comparison.
