### ISSUE TITLE
Face detection doesn't work correctly

### ISSUE THREAD

**Issue by danicomas** [liuliu/ccv#116]
I have tested with this image.
![picture](https://cloud.githubusercontent.com/assets/4038192/4934851/10dd8f0e-65a6-11e4-86c1-6a6cfd5b2e52.jpg)
![result](https://cloud.githubusercontent.com/assets/4038192/4934866/32964c8a-65a6-11e4-8b03-fc7beb9c8e77.PNG)

**Comment by liuliu** [comment]
This is expected from the old BBF detector. I am working on a more accurate version (ccv_scd.c) but haven't finished yet.
