### ISSUE TITLE
siftmatch seg fault

### ISSUE THREAD

**Issue by JaredMistretta** [liuliu/ccv#117]
The siftmatch program is seg faulting on me. It seems to be occurring inside the ccv_sift() function. My os is ubuntu 14.04. Thanks for the help.

**Comment by liuliu** [comment]
Is it possible to share with me what image you ran against?

```
./siftmatch ../samples/scene.png ../samples/basmati.png
```

doesn't segfault for me on latest.

**Comment by JaredMistretta** [comment]
./siftmatch ../samples/book.png ../samples/scene.png

I just used the command from the SIFT documentation post. The other image did the same.

**Comment by liuliu** [comment]
Do you have a stacktrace on this? I cannot reprod this problem and was wondering what could go wrong here.

**Comment by JaredMistretta** [comment]
Sorry for not getting back sooner. The problem was tracked down to not haveing libpng installed. The default read function didn't seem to be properly working. 

New error from the ruby program:

./siftdraw.rb:30:in ``': No such file or directory - convert ../samples/book.png -extent 850x384 output.png (Errno::ENOENT)
    from ./siftdraw.rb:30:in`<main>'

My ruby knowledge is very limited. Any suggestions for fix?

**Comment by liuliu** [comment]
You need to install imagemagick, "convert" is its binary.
