### ISSUE TITLE
opencv 2.4.9 issue and its possible solution

### ISSUE THREAD

**Issue by bittnt** [liuliu/ccv#123]
Hi, @liuliu , I found a bug in the current ccv code for the opencv, and i also found a solution for it.

So you might find that cvaux is not in opencv 2.4.9 anymore. You would get an error saying:
cvCvtColor undefined
and 
/usr/bin/ld: cannot find -lopencv_cvaux
collect2: error: ld returned 1 exit status

The solution to fix them is to have a slight different Makefile:
OPENCV = /opt/opencv
CXX = g++
LINKFLAG = -L/opt/opencv/lib -lopencv_core -lopencv_highgui -lopencv_imgproc -pthread
INCFLAGS = -I"/opt/opencv/include"
CXXFLAGS = -O2 --fast-math -msse2

you might change your opencv path depends on how you install opencv.

Otherwise, the code is excellent.

**Comment by liuliu** [comment]
Thanks! The opencv code was meant to benchmark against opencv for these implementations. I removed the code in preparation for 0.7 release. Thanks for the notes though!
