### ISSUE TITLE
Build error in ccv/bin on NVIDIA Jetson TK1 board 

### ISSUE THREAD

**Issue by SeokhyunKim** [liuliu/ccv#127]
Hello.
I'm sw engineer of Software R&D Center, Samsung electronics.

Recently, I tested libccv on NVIDIA Jetson TK1 board.
I wanted to compile cnnclassify.c in ccv/bin folder, and got the following error messages:

make -C ../lib
make[1]: Entering directory `/home/ubuntu/workspace/ccv/lib'
make[1]: Nothing to be done for`all'.
make[1]: Leaving directory `/home/ubuntu/workspace/ccv/lib'
gcc -o bbffmt bbffmt.o -L"../lib" -lccv -L/usr/local/lib -lm -lpng -ljpeg -lcuda -lcudart -lcublas -l/usr/local/cuda/lib
/usr/bin/ld: cannot find -lcudart
/usr/bin/ld: cannot find -lcublas
/usr/bin/ld: cannot find -l/usr/local/cuda/lib
collect2: error: ld returned 1 exit status
make: **\* [bbffmt] Error 1

This may be simple problem, and if you want I could make a simple bug fix patch.
Thank you.

**Comment by mbertini** [comment]
Try changing that -l/usr/local/cuda/lib to -L/usr/local/cuda/lib and check that /usr/local/cuda/lib actually contains the cud library files (those that are required by the -lcuda parameter)

**Comment by SeokhyunKim** [comment]
Yes it solved by your comment. Thank you, mbertini.
It would be good if the configure script in ccv/lib is modified for this problem, I think.

**Comment by ghost** [comment]
@SeokhyunKim @mbertini 
can i run ccv on CPU and can you provide me a step by step procedure for installation of ccv in ubuntu
