### ISSUE TITLE
Bindings for JVM, Haskell, Python, etc?

### ISSUE THREAD

**Issue by erikkaplun** [liuliu/ccv#128]
Are there any plans to release wrappers for the JVM, Haskell or other languages?  Even very basic, "raw" wrappers around the bare C library would be better than nothing.

**Comment by liuliu** [comment]
Hey, @eallik , that requires some substantial change to the philosophy (http://libccv.org/post/an-elephant-in-the-room/), I'd prefer other languages to interact with its HTTP service (http://libccv.org/doc/doc-http/) directly in most cases, in a few cases you actually need to have a wrapper, it probably won't be in the main codebase (I do want a JNI interface, but again, not in the main codebase).
