### ISSUE TITLE
clearer documentation of installation process

### ISSUE THREAD

**Issue by kylemcdonald** [liuliu/ccv#131]
thank you for ccv! i've been following it for a while but am just now getting into it. your very open imagenet network has gotten me very interested :)

i'm on OSX 10.9.5 on a late 2013 macbook pro. to get it working i had to do the following. first i installed the cuda developer tools, then:

``` sh
echo 'export PATH=/usr/local/cuda/bin:$PATH
export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:$DYLD_LIBRARY_PATH' >>~/.bash_profile
cd ~
git clone https://github.com/liuliu/ccv.git
cd ccv/lib
./configure
make
cp libccv.a /usr/lib/
cp ccv.h /usr/include/
cd ../
make
```

then i tested:

```
$ ./cnnclassify ../samples/nature.png ../samples/image-net-2012-vgg-d.sqlite3
74 0.200349 159 0.160961 48 0.155379 1 0.107324 62 0.101437
elapsed time 1995ms
```

and looking at `image-net-2012.words` 74 is "mongoose" which is almost like a raccoon -- awesome!

the only difficulty was that two of the steps above were not very clear to me:
1. adding to the PATH and DYLD_LIBRARY_PATH variables
2. installing libccv to /usr/lib and /usr/include

is there somewhere i could add more info about these steps to help others?

edit: it looks like the make file for bin/ actually references the libs in ../lib so maybe the cp step isn't necessary? but for anything using -lccv it's clearly necessary. if this is all should be "obvious" then please feel free to close this issue :)

**Comment by kylemcdonald** [comment]
after getting all this to work, i realized i haven't actually been able to use the CUDA/GPU cnn implementation -- i've just been using the CPU version :(

here's a simple demo of the problem:

```
kyle:bin kyle$ ./cnnclassify ../samples/dex.png ../samples/image-net-2012.sqlite3
113 0.189956 89 0.150560 189 0.123655 84 0.086437 173 0.076506
elapsed time 401ms
kyle:bin kyle$ echo "../samples/dex.png" > files.txt
kyle:bin kyle$ ./cnnclassify files.txt ../samples/image-net-2012.sqlite3
Assertion failed: (layers[i].w), function _cwc_convnet_alloc_layers, file cuda/cwc_convnet.cu, line 158.
Abort trap: 6
```

here is the log from the entire build process https://gist.github.com/kylemcdonald/f4071f48c04df0786234 there are a couple minor warnings but i don't see anything significant.

i've also updated to 10.10.2 and noticed there were a few things i'd already done that i needed to repeat:

```
brew install libjpeg libpng liblinear fftw gsl tesseract
xcode-select --install
```

not all those libs are necessary, but i figured i might as well grab everything. the second line was important for adding `/usr/local/include` to the path so that `./configure` could see that these libraries were installed. if i ignored either of these steps, running `./cnnclassify` would not be able to load images due to the missing libjpeg or libpng (i somehow missed the output of `./configure` initially and ran `make` anyway).

last week i was able to compile libccv for CUDA on an ubuntu 14.04 system and it was lovely, now i really want it on OS X too :) any advice is highly appreciated.

**Comment by kylemcdonald** [comment]
without any response, i'll assume these details are just normal.

i also saw in #109 that the 2GB memory on my card may not be enough to store the model for GPU processing, which answers the "Assertion failed" problem.

again, if there is interest in either updating the documentation or maybe adding a message to the assert failure to guide people running into the same problem, let me know and i'd be happy to try contributing.

thanks again!

**Comment by liuliu** [comment]
Sorry that I was occupied by other priorities in life and didn't have a chance to look at this in past month.

**Comment by kylemcdonald** [comment]
No need to apologize! It's your project, on your time :) Thanks again!

**Comment by liuliu** [comment]
Thanks for the help!
