### ISSUE TITLE
Question: image compression use face detection as heuristic

### ISSUE THREAD

**Issue by morenoh149** [liuliu/ccv#133]
Has anyone ever used face detection as a heuristic for image compression?
How would one develop this?

meaning, detect regions of a photo with faces.
Compress these regions less than the other parts of the photo.

**Comment by liuliu** [comment]
I don't see anything particular on this. Feel free to start a new GitHub project on this. The direction probably should be 1). Find faces in original photo; 2). Do compression as normal; 3). Do de-compression and then get the diff between original and compressed around faces; 4). Save the diff separately (do Huffman encoding all over again probably) into metadata.

Reverse the steps to recover.

**Comment by morenoh149** [comment]
started it here https://github.com/morenoh149/FaceCompress
:+1:
