### ISSUE TITLE
Training classifier

### ISSUE THREAD

**Issue by weiyt2014** [liuliu/ccv#140]
I see your scd.md .training process use aflw dataset. Now i want to use our dataset to train our own classifier. I see " AFLW dataset provided a SQLite file". If our image don't have  SQLite file,how to create it? If  no SQLite file ,whether training to go on? Thanks very much!

**Comment by liuliu** [comment]
Hey, all scdcreate cares is a list of file and its x, y, width, height (if you read the output of the sqlite file in the document, you will see exactly what it needs). You don't need a sqlite file as AFLW to proceed.
