### ISSUE TITLE
Zip file can't download sqlite db

### ISSUE THREAD

**Issue by lababidi** [liuliu/ccv#142]
Download .zip file from libccv.org webpage, ran ./configure and then make and got the following error:

`fatal: Not a git repository (or any of the parent directories): .git
../samples/download-vgg-d-model.sh: 3: cd: can't cd to /samples
make: *** [../samples/image-net-2012-vgg-d.sqlite3] Error 2`

**Comment by liuliu** [comment]
Thanks. Yeah, that case is not tested, I assumed it has a git repo somewhere so that I can find the download script.

**Comment by mbirkhez** [comment]
Hi, I get the same error. Does anybody know how to solve it?

**Comment by liuliu** [comment]
Try to git clone the repo, or simply do make afterwards. That error is not critical (basically you didn't download the vgg-d model).

**Comment by morenoh149** [comment]
it's from executing https://github.com/liuliu/ccv/blob/stable/samples/download-vgg-d-model.sh#L3

the zip download seems to lack the `.git` version control dir so when `git rev-parse --show-toplevel` gets run the system throws an error
