### ISSUE TITLE
Infinite loop in ccv_bbf_detect_objects

### ISSUE THREAD

**Issue by jpolsonaz** [liuliu/ccv#152]
ccv_bbf_detect_objects gets in an infinite loop if a detection is at the far right or bottom of an image.  Here's a patch which fixes the problem.

diff --git a/lib/ccv_bbf.c b/lib/ccv_bbf.c
index 7c6754a..4f115da 100644
--- a/lib/ccv_bbf.c
+++ b/lib/ccv_bbf.c
@@ -209,7 +209,7 @@ static int _ccv_prepare_background_data(ccv_bbf_classifier_cascade_t\* cascade, c
                            break;
                        }
                    rect = (ccv_rect_t*)ccv_array_get(detected, r);
-                   if ((rect->x < 0) || (rect->y < 0) || (rect->width + rect->x >= image->cols) || (rect->height + rect->y >= image->rows))
-                   if ((rect->x < 0) || (rect->y < 0) || (rect->width + rect->x > image->cols) || (rect->height + rect->y > image->rows))
                  {
                      flag = 1;
                      r = gsl_rng_uniform_int(rng, detected->rnum);

**Comment by gpip** [comment]
@jpolsonaz hey, not a ccv maintainer, but could you re-format your post using backticks so github doesn't interpret it as markdown? The bullet points in particular are confusing :)

**Comment by liuliu** [comment]
Thanks, I will look into this and fix all the places this may get wrong later today.

**Comment by liuliu** [comment]
https://github.com/liuliu/ccv/commit/1ea131e459193ffeafc4d12c05918f2ebc167c2f
