### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by morenoh149** [liuliu/ccv#160]
hello @liuliu just wondering what's the status of this project.
Do you need a custodian? I'm sure many watchers of this project would be happy to merge some PR for you. Best.

**Comment by liuliu** [comment]
Hey. Thanks for the reminder. 2015 is pretty stalled. I am ramping up on the new ccv/lib/nnc portion (which is a better interface for convnet part of ccv).

The future plan includes integrating Fast-RCNN and basically convnetify most part of ccv with the new nnc structure.

Working in startup (Snapchat) is totally a different beast. Not as much free time as I would like to have comparing with big ones (Facebook).

**Comment by morenoh149** [comment]
okay good. I was looking into how to possibly link ccv into react native. I'll let you if anything comes up.
