### ISSUE TITLE
grab all activations in convolutional/pooling layer

### ISSUE THREAD

**Issue by genekogan** [liuliu/ccv#166]
how do you get all of the activation maps from a convolutional/pooling layer? i understand how encode copies the activations from a fully-connected layer, but in one of the earlier layers where multiple feature maps are activated, how do you grab each one individually? 

so for example i set the count of the convnet (AlexNet from imagenet 2012) to 9 for 9th layer.

```
convnet->count = 9
ccv_dense_matrix_t* input = 0;
ccv_size_t size = ccv_size(225, 225);
ccv_convnet_input_formation(size, &image, &input);
ccv_dense_matrix_t* b = 0;
ccv_convnet_encode(convnet, &input, &b, 1);
```

b is 13x13 but this must just be just the first one? how would you grab each of them individually?

**Comment by liuliu** [comment]
It is 13x13xchannel size. The output is a typical ccv_dense_matrix_t layout (think about the RGB image layout).

**Comment by genekogan** [comment]
right, channel size is always 3 for RGB, but how many individual 3-channel feature maps?
for example, in AlexNet, the first convolutional layer produces 96 individual feature maps of 55x55x3. are all of these encoded into `b->data.f32`? is there a field which counts how many there are for a particular layer?

**Comment by liuliu** [comment]
CCV_GET_CHANNEL(output->type) Try this.

**Comment by genekogan** [comment]
thanks! that worked perfectly.
btw this is all for [ofxCcv](https://github.com/kylemcdonald/ofxCcv) which is a library for wrapping ccv for [openframeworks](https://github.com/kylemcdonald/ofxCcv).
