### ISSUE TITLE
Converting or training new cascade

### ISSUE THREAD

**Issue by xthepoet** [liuliu/ccv#17]
The face.js looks like a stage classifier cascade similar to what's used in OpenCV. Is it possible to convert the existing OpenCV Haar or LBP classifiers to your format, and if so, how is it done? Alternatively, do you have a training algorithm for the cascade which can be used as face.js?

**Comment by liuliu** [comment]
No, it uses different feature. See: http://libccv.org/doc/doc-bbf/ for how to train your classifier. ./bin/bbffmt is the program to take a classifier and output a json data.

**Comment by xthepoet** [comment]
Thanks

On Mon, Jul 9, 2012 at 12:47 PM, Liu Liu
reply@reply.github.com
wrote:

**Comment by rafaelfaria** [comment]
Do you have, or know where I can find anyone that manage to train a mouth cascade for your format?!
