### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by dajuric** [liuliu/ccv#174]
I apologize, I did not know where to put this question. I would be grateful if you could answer it.
Thank you.

I have noticed that TLD implementation is also incorporated. Since the implementation is written from the scratch and is modified is it OK to use it under BSD license (the original code forces GPLv3 license) ?

Thanks.

**Comment by liuliu** [comment]
It is a from scratch implementation under BSD license.

**Comment by dajuric** [comment]
Thanks :)
