### ISSUE TITLE
TLD performance

### ISSUE THREAD

**Issue by dajuric** [liuliu/ccv#175]
I managed to compile the code for TLD tracker for Windows (VS 2015).
It works, but the speed (FPS) is considerably lower than OpenTLD implementation (binaries): https://github.com/gnebehay/OpenTLD/downloads

(~3 FPS to ~15 FPS,) on 320x240 video)

I am just wondering, am I doing something wrong, or this FPS is OK ?

Thank you.

![perf](https://cloud.githubusercontent.com/assets/4395047/14369129/b71e2fc6-fd22-11e5-9754-b5e552c3d9e2.jpg)

**Comment by liuliu** [comment]
Depends on your configuration. Also, compile with -O3 will help a ton. ccv_tld_default_params gives you the configuration that on a typical Linux box (i7 6700k), it will be around 20 to 30fps.

**Comment by dajuric** [comment]
Thanks for the suggestion. I will try that. (the provided parameters are used)

**Comment by peruginia** [comment]
Hy, i have read you have succesful compiled libccv on windows with mingw...

i have succesfull compiled (./configure and make ) the library (/lib) but when i try to compile the example in /bin i succesful compile bbffmt and on msermatch i receive this error : 

gcc -o msermatch msermatch.o -L"../lib" -lccv -L/usr/local/lib -lm
../lib/libccv.a(ccv_io.o):ccv_io.c:(.text+0x7ef): undefined reference to `fmemopen'
collect2.exe: error: ld returned 1 exit status
make: **\* [msermatch] Error 1

can you help me on solve this problem?

**Comment by dajuric** [comment]
Oh, I compiled it using Visual Studio 2015.
But I had to replace macros with simple versions for a specific data types
(that was time consuming) + things that are mentioned under Windows
compilation issue.
I also trimmed the library as I only needed TLD algorithm.

2016-04-09 12:09 GMT+02:00 peruginia notifications@github.com:

**Comment by liuliu** [comment]
Type could be important, most tld is working on u8 (uint8_t). Let me know what you've figured out. Also, OpenTLD could have a lighter parameters than tld_default_params, which can impact the performance dramatically.

**Comment by dajuric** [comment]
As I remember, I used u8 parameters on all functions in ccv library. But
still... OpenTLD outperforms it in terms of speed and accuracy (at least
for a tested video).
Nevertheless, if/when I compare those two I will let you know (this
challenge also bugs me too :))

Best,
Darko

2016-04-10 22:47 GMT+02:00 Liu Liu notifications@github.com:
