### ISSUE TITLE
Assertion 'argc>=3' failed

### ISSUE THREAD

**Issue by rainbow0727** [liuliu/ccv#180]
I use this command,but always  get failed
./scddetect  <K.jpg>  ../samples/face.sqlite3 | sudo sh bbfdraw.rb  <K.jpg>  output.jpg
./scddetect  <Koala.jpg>  ../samples/face.sqlite3 | sudo sh bbfdraw.rb  <Koala.jpg>  output.jpg

**Comment by rainbow0727** [comment]
@liuliu

**Comment by liuliu** [comment]
./scddetect ../someimagefile ../samples/face.sqlite3. See the example: http://libccv.org/doc/doc-scd/
