### ISSUE TITLE
Reproducible segfault with cct_swt_detect_words

### ISSUE THREAD

**Issue by Yoric** [liuliu/ccv#192]
STR:
1. Build libccv with libjpeg support.
2. Build `swtdetect`.
3. Run on the following sample:
   ![incredients](https://cloud.githubusercontent.com/assets/10190/18833863/25c9c2e4-83f3-11e6-880b-ecbbc6f0f951.jpeg)

Results: Segfault.

Observed on MacsOS 10.11.6, running clang. `clang -v` produces `Apple LLVM version 8.0.0 (clang-800.0.38)`.

**Comment by liuliu** [comment]
Thanks. Very helpful. Will do a diagnostic run later today.

**Comment by Yoric** [comment]
Oh, false alert. This build didn't have libjpeg support and I was trying to load a jpeg image.

Apologies for the noise.
