### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by stevegraham** [liuliu/ccv#20]
Hi @liuliu,

It would be extraordinarily useful for CV n00bs, e.g. myself, if there was sample code for each of the functions, specifically for ccv_swt. It would be awesome it someone could contribute that.

Thank you for releasing this library.

S

**Comment by liuliu** [comment]
There are example codes in ./bin folder, but it is lightly documented. ccv_swt is under documented because I am going to implement a new one, which should be more stable and easy to use.
