### ISSUE TITLE
Installation failed on Ubuntu 18.04

### ISSUE THREAD

**Issue by sendjasni** [liuliu/ccv#210]
I followed the instruction from the getting started tutorial on the Libccv web site, but I think it didn't work, I don't know why. This is the last lines after executing the ** ./configure && make ** command :

`
gcc ccv_algebra.c -o ccv_algebra.o -c -O3 -ffast-math -Wall -msse2 -D HAVE_LIBPNG -D HAVE_LIBJPEG -D HAVE_AVCODEC -D HAVE_AVFORMAT -D HAVE_SWSCALE -D HAVE_SSE2 -I/usr/local/include
gcc ccv_util.c -o ccv_util.o -c -O3 -ffast-math -Wall -msse2 -D HAVE_LIBPNG -D HAVE_LIBJPEG -D HAVE_AVCODEC -D HAVE_AVFORMAT -D HAVE_SWSCALE -D HAVE_SSE2 -I/usr/local/include
gcc ccv_basic.c -o ccv_basic.o -c -O3 -ffast-math -Wall -msse2 -D HAVE_LIBPNG -D HAVE_LIBJPEG -D HAVE_AVCODEC -D HAVE_AVFORMAT -D HAVE_SWSCALE -D HAVE_SSE2 -I/usr/local/include
gcc ccv_image_processing.c -o ccv_image_processing.o -c -O3 -ffast-math -Wall -msse2 -D HAVE_LIBPNG -D HAVE_LIBJPEG -D HAVE_AVCODEC -D HAVE_AVFORMAT -D HAVE_SWSCALE -D HAVE_SSE2 -I/usr/local/include
gcc ccv_resample.c -o ccv_resample.o -c -O3 -ffast-math -Wall -msse2 -D HAVE_LIBPNG -D HAVE_LIBJPEG -D HAVE_AVCODEC -D HAVE_AVFORMAT -D HAVE_SWSCALE -D HAVE_SSE2 -I/usr/local/include

cc1: out of memory allocating 65536 bytes after a total of 5508444160 bytes
makefile:27: recipe for target 'ccv_resample.o' failed
make: *** [ccv_resample.o] Error 1
`

**Comment by liuliu** [comment]
This is out of memory issue. With GCC, it requires at least 16GiB memory computer to compile. Clang has much less requirement. Won't fix this until we are close to release and I need to revisit ccv part.
