### ISSUE TITLE
Installation failed on Ubuntu 18.04

### ISSUE THREAD

**Issue by sendjasni** [liuliu/ccv#212]
After executing the fillowing  command in order to install the ccv lib :

**./configure --disable-openmp && make lib && cd ../bin && make && cd ../site && make source && cd ../test && make && make test**

I got tthe following output :

...
...
....
23 warnings and 3 errors generated.
makefile:28: recipe for target 'tld.o' failed
make: *** [tld.o] Error 1

**Comment by MatthewScholefield** [comment]
There's a compiler error somewhere above that which should have more info.

**Comment by Ryy2737** [comment]
Hi, @sendjasni did you find solution for  "recipe for target 'tld.o' failed"

**Comment by sendjasni** [comment]
@Ryy2737 actually I gave up on using the libccv. Sorry, I can't help you more.
