### ISSUE TITLE
Issue ccv_read - assertion failed at scddetect

### ISSUE THREAD

**Issue by carlosost** [liuliu/ccv#214]
Steps to help replicate the scenario:

1. Clone ccv git repository
2. cd lib
3. autoconf configure.ac > configure
4. ./configure
5. cd ../bin
6. make all
7. /scddetect ../samples/lena.png ../samples/face.sqlite3

Than I get this error message:
scddetect: scddetect.c:49: int main(int, char * *): Assertion `image != 0' failed.
Aborted (core dumped)

Trying to solve the problem and following some foruns I've found, I installed two libs to deal with png and jpeg files, like bellow:

8. sudo yum install libpng-devel
9. sudo yum install libjpeg-turbo-devel
10. Returned to step 2 through 7

But I am still getting the error. Any help?

**Comment by carlosost** [comment]
I have changed the third line of makefile at ../bin directory like bellow, including what I think is the linking tags for libpng and libjpeg, but I am still getting the same error.

LDFLAGS := -L"../lib" -lccv **-L"/usr/lib64" -lpng -ljpeg** $(LDFLAGS)

**Comment by liuliu** [comment]
In the generated config.mk file (./lib/config.mk), if it cannot find libpng / libjpeg, you have to manually modify such that:
```
DEFINE_MACROS := -D HAVE_LIBPNG -D HAVE_LIBJPEG
LDFLAGS :=  -L${exec_prefix}/lib -lpng -ljpeg
```
and then do a make clean / make

**Comment by carlosost** [comment]
Thank you @liuliu . It worked!!!

Just for others with the same "problem", I folllowed your instructions like bellow:

- I edited ./lib/config.mk like you've suggested
- called make clean
- called make
- cd ../bin
- called make 
- executed ./scddetect ../samples/lena.png ../samples/face.sqlite3  

Thank you so much!
