### ISSUE TITLE
cv::Mat to ccv_dense_matrix_t*

### ISSUE THREAD

**Issue by carlosost** [liuliu/ccv#226]
Is there a way to convert an image from `cv::Mat` format into a `ccv_dense_matrix_t*`?

**Comment by liuliu** [comment]
Either use the last `ccv_read` method to copy that buffer over: https://libccv.org/lib/ccv-io/#ccvread-2 or use `ccv_dense_matrix_new` to pass the proper formatted buffer (i.e., not owned, you have to make sure the lifetime is correct) in the last parameter: https://libccv.org/lib/ccv-memory/#ccvdensematrixnew
