### ISSUE TITLE
Compilation error (and fix)

### ISSUE THREAD

**Issue by abetusk** [liuliu/ccv#23]
When trying to run 'make' in the 'bin' directory, I get the following compilation errors:

$ make
make -C ../lib
make[1]: Entering directory `/home/abetusk/Downloads/liuliu-ccv-43ec190/lib'

 USE: clang
 COMPILE FLAGS: -msse2 -D HAVE_SSE2 -D HAVE_LIBJPEG -D HAVE_LIBPNG -D HAVE_GSL -D HAVE_FFTW3 -D HAVE_LIBLINEAR -D HAVE_CBLAS
 LINK FLAGS: -lm -ljpeg -lpng -lz -lgsl -lfftw3f -lfftw3 -llinear -lblas

make[2]: Entering directory `/home/abetusk/Downloads/liuliu-ccv-43ec190/lib'
make[2]: Nothing to be done for`all'.
make[2]: Leaving directory `/home/abetusk/Downloads/liuliu-ccv-43ec190/lib'
make[1]: Leaving directory`/home/abetusk/Downloads/liuliu-ccv-43ec190/lib'
clang -o bbffmt bbffmt.o -L../lib -lccv -lm -ljpeg -lpng -lz -lgsl -lfftw3f -lfftw3 -llinear -lblas 
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../libgsl.so: undefined reference to `cblas_ctrmv'
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../libgsl.so: undefined reference to`cblas_zswap'
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../libgsl.so: undefined reference to `cblas_zsymm'
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../libgsl.so: undefined reference to`cblas_cgeru'
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../libgsl.so: undefined reference to `cblas_sgemm'
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../libgsl.so: undefined reference to`cblas_ctrsv'
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../libgsl.so: undefined reference to `cblas_sgemv'
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../libgsl.so: undefined reference to`cblas_srotg'
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../libgsl.so: undefined reference to `cblas_zgemm'
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../libgsl.so: undefined reference to`cblas_cdotu_sub'
...

/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../libgsl.so: undefined reference to `cblas_daxpy'
/usr/lib/gcc/x86_64-linux-gnu/4.6/../../../libgsl.so: undefined reference to`cblas_csyrk'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [bbffmt] Error 1

Adding ' -lgslcblas' to the end of the '../lib/.LN' file seems to fix the problem for me.

**Comment by haarts** [comment]
+1
The solution worked for me.
