### ISSUE TITLE
mac setup line 3 is difficult to understand

### ISSUE THREAD

**Issue by enzyme69** [liuliu/ccv#233]
I have followed the procedure and got bazel installed but step 3 is very hard to understand. can you explain?

`Add .bazel.local file, with one line: build --config=mps`

**Comment by enzyme69** [comment]
Totally not familiar with .dot file but I kind of make a text file and then following this:
https://stackoverflow.com/questions/5891365/mac-os-x-doesnt-allow-to-name-files-starting-with-a-dot-how-do-i-name-the-hta

**Comment by liuliu** [comment]
Something like running this in your command line:
```
echo "build --config=mps" > .bazelrc.local
```
