### ISSUE TITLE
missing ccv_bbf_params_t

### ISSUE THREAD

**Issue by yunfan** [liuliu/ccv#24]
hi , i compiled ccv , it works from the builtin samples

but i found the face detect sample on the website (http://libccv.org/galaxy-guide/) couldnt be compiled

is this a outdate document? (by greping ccv_bbf_params_t in the top of soucecode directory, i found nothing)

**Comment by liuliu** [comment]
that's a typo, should be ccv_bbf_param_t, fixed in the doc. You can find the exact program in ./bin/bbfdetect.c

**Comment by yunfan** [comment]
hi i have just test the human face detecting, its cool ,

but for recognizing player role from network game like wow, its not works, i know its the pattern data things

could you please offer any trainning tools ?

**Comment by liuliu** [comment]
http://libccv.org/doc/doc-bbf/#how-to-train-my-own-detector
