### ISSUE TITLE
Compiling in Visual Studio

### ISSUE THREAD

**Issue by minyongyoon** [liuliu/ccv#26]
Hi,

I am completely noob about cross compiling and related. I usuallly program in C++ in Visual Studio, but I can't not figure out how to compile this project to be used in Visual Studio. I also made some small projects using gcc.

My first attempt has been to use CMake. No idea where to start lol

After that, I tried to compile with Mingw and MSYS. I just had to change some headers, like alloca.h by malloc.h , unitsd.h  by .... I dont remember exactly how, but it compiled. The problem is, now I have some linux-like static library, and I am not able to link it from Visual Studio.

Third attempt was to add the files directly to my Visual Studio c++ project, but too many compiling errors.

Could you give some clues to achieve this? Does this issue have some relationship to another Issue about compiling in win32 using dmake? What is dmake?

Thanks.

**Comment by koudelka** [comment]
Check out issue #18, that might give you a starting place to use CMake.

**Comment by avmich** [comment]
Hi,

I'm modifying the libccv to compile example "Getting Started" In Visual Studio (2012, but don't think it's important). Many errors go away after #include < io.h > /\* instead of unistd.h \* /, moving variable declarations to the start of the functions (not sure why, may be project default settings are such...), linking with ws2_32.lib (I have Windows 7 32 bit), #define  alloca _alloca /\* all such changes are in ccv.h \* / .

But then ccv_util.c refuses to compile - the problem is in nested macros, starting from ccv_declare_derived_signature. I'm trying to change that to make it compiling in MSVC, but so far fail to understand the idea. Don't want to change macros too radically.

Can this part be simplified? What's the reason for that macro system, can it be written simpler?

Thanks.

**Comment by avmich** [comment]
Preprocessing ccv_util.c produces the following line for ccv_object_return_if_cached(, db); :

   { if ((!(db, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0) || (((int_)(db, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE)) && (!() || (((int_)())[0] & CCV_GARBAGE))) { (void)((db, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0) && (((int_)(db, 0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0))[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));(void)(() && (((int_)())[0] &= ~CCV_GARBAGE));;; return ; } };

Is this correct? Any comments on this? MSVS complains "C4003: not enough actual parameters for macro 'INTERNAL_GARBAGE_TYPEDEF_CONCATENATE_IN'" .

**Comment by liuliu** [comment]
MSVC cannot compile ccv source code. If you want to use it under Windows, using MinGW to compile a dll or lib file and then link to it.

**Comment by lxd4** [comment]
I would like to comment that I don't think visual studio is capable of using a static build of ccv from mingw, due to the fact that the c standard library supported by mingw differs from the c standard library implemented in visual studio. In particular, ccv will link dynamically to symbols like chkstk_ms and emutls_get_address that visual studio cannot resolve.

**Comment by leonidk** [comment]
I would like to point out that, with minimal changes, [LLVM 3.6 on VS2013](http://llvm.org/releases/download.html) will compile all the code in ccv/lib into a static lib or dll. The following code snippet constitutes most of the required changes for a successful complication. However, I can't attest to trying any samples on top of this quite yet (e.g. maybe the lib+dll are broken). If I build it successfully, I'll issue a pull request for a complete patch. 

```
#if defined(_MSC_VER)
#include <malloc.h>
#define alloca _alloca
#define snprintf _snprintf
typedef __int32 int32_t;
typedef unsigned __int32 uint32_t;
typedef __int64 int64_t;
typedef unsigned __int64 uint64_t;
# define BSWAP32(x)  ((((x) & 0x000000ff) << 24) |      \
                      (((x) & 0x0000ff00) << 8)  |      \
                      (((x) & 0x00ff0000) >> 8)  |      \
                      (((x) & 0xff000000) >> 24));
#define inline __inline 
#endif
```

Update: I've gotten a few samples to compile and link, but none of them seem to behave correctly. I'm not sure if it's my modifications, LLVM's WIP implementation or what, but I'll hack on this periodically and post an update if I get anything meaningful working.

**Comment by liuliu** [comment]
Thanks, will look forward the PR!
