### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [liuliu/ccv#3]
I would like to point out that identifiers like "[`_GUARD_ccv_h_`](https://github.com/liuliu/ccv/blob/53007a47087698b55508fbdba8a4a95d7ae1d261/lib/ccv.h#L6)" and "[`__ccv_resample_area_8u`](https://github.com/liuliu/ccv/blob/e580c487accd26eb9bb0c3ab9b243918e70d2f24/lib/ccv_basic.c#L483)" [do not fit](https://www.securecoding.cert.org/confluence/display/seccode/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming conventions of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by liuliu** [comment]
thanks. I will include those modifications in newer version. currently I am working on dpm implementation.

**Comment by liuliu** [comment]
I've fixed this in unstable branch. thanks for the feedback
