### ISSUE TITLE
Thread-local storage is unsupported for iOS

### ISSUE THREAD

**Issue by mledford** [liuliu/ccv#30]
The following occurs when trying to build off the r0.2-rc1 branch in Xcode:

> ccv/lib/ccv_memory.c:5:8: error: thread-local storage is unsupported for the current target
> static __thread ccv_cache_t ccv_cache;
>      ^
> 
> ccv/lib/ccv_memory.c:14:8: error: thread-local storage is unsupported for the current target
> static __thread int ccv_cache_opt = 0;
>       ^

Did some digging and found the following post about [thread-local storage and iOS](http://stackoverflow.com/questions/6557768/thread-local-storage-and-ios). http://stackoverflow.com/questions/6557768/thread-local-storage-and-ios

How do you suggest fixing this one?

**Comment by mledford** [comment]
I've done a little more research into this. I haven't encountered the __thread specifier before so this was a good chance to learn something new. The following article I found nicely explains some of what is going on: http://lifecs.likai.org/2010/05/mac-os-x-thread-local-storage.html.

It seems like the most portable thing to do is use POSIX pthread_setspecific() and pthread_getspecific(). If this sounds reasonable I will be happy to implement it.

**Comment by liuliu** [comment]
Thanks @mledford, if we want to take on pthread dependency, a better way is not thread-local storage, but put a plain-old rw lock around cache access. I haven't figured out details yet about how to do that just yet. In the mean time, a patch that solves iOS problem is most appreciated (you can either remove the modifier for iOS target or using pthread as fallback, I guess).
