### ISSUE TITLE
How to create a new classifier for the JS implementation?

### ISSUE THREAD

**Issue by jmedding** [liuliu/ccv#35]
Hello,

I was reading though your explanation of javascript face detection here: http://liuliu.me/eyes/javascript-face-detection-explained

and i was wondering what you would have to do to also detect the eyes and mouth positions in a face. I assume that you would have to create new classifiers and then pass the portion of the image that has a face into the function with the correct classifier.

My question is, can I create a classifier for your cvv.js using this process and tool?

https://github.com/liuliu/ccv/blob/stable/doc/bbf.md

Thanks and best regards,
Jonathan

**Comment by liuliu** [comment]
Yes, you can create one with the bbfcreate CLI, and then with bbffmt CLI, you can convert the generated classifier to JSON format, and start from there.

**Comment by jmedding** [comment]
Many thanks!
