### ISSUE TITLE
Error when building for HTTP

### ISSUE THREAD

**Issue by moreli** [liuliu/ccv#51]
I'm getting the following error when trying to the HTTP build <pre>cd serve/ && make && ./ccv</pre>

<pre>make[1]: *** No rule to make target `ccv_icf.o', needed by `libccv.a'.  Stop.
make: *** [libccv.a] Error 2</pre>

I'm running on mac 10.8 and this is my config.mk
<pre>
XCODE_SDK := macosx10.8
ARCH := x86_64
CC := clang
AR := ar
CFLAGS := -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk 
LDFLAGS := -lm -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.8.sdk 
</pre>

Any ideas?

**Comment by mledford** [comment]
The makefile located in ./lib currently has a spurious entry at the end of line 13. Remove "ccv_icf.o" save and you should be able to build.

**Comment by liuliu** [comment]
As a side note, for any real usage, try to stay on stable branch, I will always introduce new features / modules to unstable branch, and the build may break sometimes.

**Comment by moreli** [comment]
Ok. Using the stable version. I'm not getting the following error:

<pre>serve.c:2:10: fatal error: 'ev.h' file not found
#include <ev.h>
         ^
1 error generated.
make: *** [serve.o] Error 1</pre>

the configure.mk is the same

**Comment by liuliu** [comment]
@moreli to build the HTTP API, you need to have libev (not libevent!) and libdispatch installed. On Mac OSX, you don't need libdispatch, but have to modify the makefile a little bit to compile. Currently, I kept it a bit manual, but with an upside (you don't have to deal with complicated build system if you know the basics about makefile).

**Comment by moreli** [comment]
@liuliu libev is installed. I don't mind the manual modifications but it fails to compile. I hope i'm doing something wrong, I just want to know what it is 
:+1: thanks for the quick response.

<pre>Elis-MacBook-Pro:ccv ***$ brew upgrade libev
Error: libev-4.11 already installed</pre>

I've modified the serve make list file as instructed and removed -libdispatch

<pre>include ../lib/config.mk
#CC += -faddress-sanitizer -fno-omit-frame-pointer
LDFLAGS := -L"../lib" -lccv -lev $(LDFLAGS)
CFLAGS := -O3 -Wall -I"../lib" $(CFLAGS)
TARGETS = ccv
all: libccv.a $(TARGETS)
clean:
    ${MAKE} clean -C ../lib ; rm -f *.o $(TARGETS) -f
$(TARGETS): serve.o uri.o parsers.o bbf.o dpm.o sift.o swt.o tld.o async.o ebb.o ebb_request_parser.o libccv.a
    $(CC) -o $@ serve.o uri.o parsers.o bbf.o dpm.o sift.o swt.o tld.o async.o ebb.o ebb_request_parser.o $(LDFLAGS)
libccv.a:
    ${MAKE} -C ../lib
ebb_request_parser.c: ebb_request_parser.rl
    ragel -s -G2 $< -o $@
%.o: %.c ../lib/ccv.h ebb.h ebb_request_parser.h
    $(CC) $< -o $@ -c $(CFLAGS)</pre>

**Comment by liuliu** [comment]
@moreli check if libev is correctly linked to /usr/local/include or /usr/include, if not, you may want to run brew link libev

For me, I noticed that libev formula in brew will install a compatibility layer with libevent, and if you have libevent installed, that may cause some problems. I unlinked libevent and can successfully link to libev afterwards.

**Comment by moreli** [comment]
@liuliu not sure what's the problem in my install, but I've added the path to libev as cflags and ldflags to serve/makefile and it works.
Thanks!!
