### ISSUE TITLE
Creating a new classifier

### ISSUE THREAD

**Issue by alexthegoodman** [liuliu/ccv#56]
Is it possible to create a new classifier to replace face.js? I am assuming that face.js is a converted version of some haarcascade xml file, yes? Could you point me in the right direction for converting other js/xml files to be used with ccv? Thanks!

**Comment by liuliu** [comment]
It is not xml / haar cascade, it is BBF. You can create a new classifier with bbfcreate.c, and convert them to javascript format with bbffmt.c
