### ISSUE TITLE
compile dpm creator liblinear locally problem 

### ISSUE THREAD

**Issue by gui2** [liuliu/ccv#62]
Hi I am trying to run dpmcreate in a cluster which has not liblinear installed (Linux). Is there a way to compile and run ccv with the dependencies "installed" locally?  I'll like a lot to avoid to use the matlab implementation. I'll really appreciate any help from the ones that have already compiled like that. (pusiol@stanford.edu).

Thnaks,
Guido.

**Comment by liuliu** [comment]
The makefile is simple enough that you can change config.mk to point it to your local liblinear installation (I believe that is as simple as -L"<your local dir>" in LDFLAGS entry.

**Comment by gui2** [comment]
Yup, it was very easy at the end. 
Thanks a lot.
