### ISSUE TITLE
provide a detector model for icf pedestrian detection

### ISSUE THREAD

**Issue by james-zhangyk** [liuliu/ccv#63]
It is great that ccv will add icf based algorithm for pedestrian detection. Hope to provide a detection model and brief usages (just like BBF, DPM, etc) to use it.

**Comment by liuliu** [comment]
I am training it :)

**Comment by bompus** [comment]
You mentioned in another comment that BBF will soon be replaced with ICF. Do you have any comparisons on the accuracy between the two? I'm looking at hooking into libccv with C# to use the functions and was going to go forward with BBF, but might wait if ICF will be available soon. Let me know - Thank you!

**Comment by liuliu** [comment]
it won't be that fast to come out. The first icf model will be plain old pedestrian, and then I need to implement multi-view support for icf, and after that, multi-view face detector.

**Comment by bompus** [comment]
Ok. I'm working on my own face recognition system but first need to accurately pick as many heads / faces from a photo of a crowd as possible. I'll work with your BBF examples for now and we'll see where ICF takes us and maybe I can even combine the two unless ICF is always going to be better than BBF or Haar. What do you think now that you've been working with it?

**Comment by liuliu** [comment]
No, I haven't finished it yet. my early test shows 60.78% (64) on INRIAPerson test set, which is worse than DPM implementation. Based on the original paper, I should expect it to be somewhere around 75% at that false positives (when FPPI is around 0.25). There are few differences contribute to the inferior result: I suspect because I use gray image is the main one.

**Comment by james-zhangyk** [comment]
Have you get good results for pedestrian detection?

**Comment by liuliu** [comment]
Not yet, but after a talk with Rodrigo, I have pretty good handle on what's going wrong with my training now.

**Comment by liuliu** [comment]
As of now, I trained a single classifier of ICF with 70% recall and 61 false alarms, which should be on par with what they reported in original paper. Training the multi-scale classifiers now.

**Comment by james-zhangyk** [comment]
great! thanks for your work.

**Comment by james-zhangyk** [comment]
just test it. It works. But the detection speed seems very slow.

**Comment by liuliu** [comment]
you can tweak step_through parameter. This is about 3 times faster than DPM one, on par or slower than HOG one. It should be as fast as the original paper, but fail short on the follow up one (Seeking the Strongest Rigid Detector one, which uses both GPU and multiple classifiers). By using multiple classifiers, I can get about ~50% performance gain (~150% faster).
