### ISSUE TITLE
Definition of ICF

### ISSUE THREAD

**Issue by bompus** [liuliu/ccv#64]
You refer to ICF as "integrate channels features" , but I believe it should be "integral channel features" - I was searching everywhere for your definition and couldn't find anything, but then came across research papers for what I think you meant. Let me know if I am correct or not. Thanks!

**Comment by liuliu** [comment]
you are right, typo

**Comment by bompus** [comment]
If you have a chance to read it, I came across this: https://bitbucket.org/rodrigob/doppia and http://rodrigob.github.io/ and I believe it uses ICF along with some other tricks to make a very fast pedestrian detector that could probably also be used for head detection. Let me know what you think ;)

**Comment by rodrigob** [comment]
If the typo has been corrected, then this issue can also be closed, right ?
