### ISSUE TITLE
Is it worthwhile submitting Win32 MSVC compilation pull requests?

### ISSUE THREAD

**Issue by bmharper** [liuliu/ccv#66]
libccv seems like a great project, but it certainly would make life easier for me if it could build on Microsoft's compiler.

A short scan through the source leads me to believe that there is actually a very small amount of gcc-specific code in there.

Would you be willing to accept pull requests aimed at compiling directly on MSVC?

**Comment by liuliu** [comment]
That would be awesome!

**Comment by bmharper** [comment]
Good to hear it.

**Comment by rodrigob** [comment]
So this issue can be closed ?

**Comment by bmharper** [comment]
Sorry for asking and then disappearing. Anyway, I believe VS 2013 adds support for C99 designated initializers, which, when I perused the code last time, seemed to be the biggest issue.
If you hear from me again, it will be with a pull request.
