### ISSUE TITLE
can't build it on MAC

### ISSUE THREAD

**Issue by sara-shafaei** [liuliu/ccv#67]
Hi,
I am trying to build and run this on MAC, I was getting this error: thread-local storage not supported for this target

I add this to make file : -pthread -E -dM
so I don't that eroor any more, but when I try to run make file in bin directory , I will get this error:
Undefined symbols for architecture x86_64:
  "_ccv_enable_default_cache", referenced from:
      _main in swtdetect.o
  "_ccv_read_impl", referenced from:
      _main in swtdetect.o
  "_ccv_array_free", referenced from:
      _main in swtdetect.o
      _ccv_swt in libccv.a(ccv_swt.o)
      _ccv_swt_detect_words in libccv.a(ccv_swt.o)
      __ccv_swt_connected_letters in libccv.a(ccv_swt.o)
      __ccv_swt_merge_textline in libccv.a(ccv_swt.o)
  "_ccv_matrix_free", referenced from:
      _main in swtdetect.o
      _ccv_swt in libccv.a(ccv_swt.o)
      _ccv_swt_detect_words in libccv.a(ccv_swt.o)
  "_ccv_drain_cache", referenced from:
      _main in swtdetect.o
  "_ccv_cache_generate_signature", referenced from:
      _ccv_swt in libccv.a(ccv_swt.o)
  "_ccv_dense_matrix_renew", referenced from:
      _ccv_swt in libccv.a(ccv_swt.o)
  "_ccv_canny", referenced from:
      _ccv_swt in libccv.a(ccv_swt.o)
  "_ccv_close_outline", referenced from:
      _ccv_swt in libccv.a(ccv_swt.o)
  "_ccv_sobel", referenced from:
      _ccv_swt in libccv.a(ccv_swt.o)
  "_ccv_array_new", referenced from:
      _ccv_swt in libccv.a(ccv_swt.o)
      __ccv_swt_connected_component in libccv.a(ccv_swt.o)
      _ccv_swt_detect_words in libccv.a(ccv_swt.o)
      __ccv_swt_connected_letters in libccv.a(ccv_swt.o)
      __ccv_swt_merge_textline in libccv.a(ccv_swt.o)
      __ccv_swt_break_words in libccv.a(ccv_swt.o)
  "_ccv_zero", referenced from:
      _ccv_swt in libccv.a(ccv_swt.o)
  "_ccv_array_push", referenced from:
      _ccv_swt in libccv.a(ccv_swt.o)
      __ccv_swt_connected_component in libccv.a(ccv_swt.o)
      _ccv_swt_detect_words in libccv.a(ccv_swt.o)
      __ccv_swt_connected_letters in libccv.a(ccv_swt.o)
      __ccv_swt_merge_textline in libccv.a(ccv_swt.o)
      __ccv_swt_break_words in libccv.a(ccv_swt.o)
  "_ccv_contour_new", referenced from:
      __ccv_swt_connected_component in libccv.a(ccv_swt.o)
  "_ccv_contour_push", referenced from:
      __ccv_swt_connected_component in libccv.a(ccv_swt.o)
  "_ccv_contour_free", referenced from:
      __ccv_swt_connected_component in libccv.a(ccv_swt.o)
      __ccv_swt_connected_letters in libccv.a(ccv_swt.o)
  "_ccv_resample", referenced from:
      _ccv_swt_detect_words in libccv.a(ccv_swt.o)
  "_ccv_sample_down", referenced from:
      _ccv_swt_detect_words in libccv.a(ccv_swt.o)
  "_ccv_array_group", referenced from:
      _ccv_swt_detect_words in libccv.a(ccv_swt.o)
      __ccv_swt_merge_textline in libccv.a(ccv_swt.o)
  "_ccv_array_zero", referenced from:
      _ccv_swt_detect_words in libccv.a(ccv_swt.o)
  "_ccv_dense_matrix", referenced from:
      __ccv_swt_break_words in libccv.a(ccv_swt.o)
  "_ccv_otsu", referenced from:
      __ccv_swt_break_words in libccv.a(ccv_swt.o)

I just want to run this SWTdetect in command line . Can you please let me know what are steps exactly to make it work. 
Thanks!
~Sara

**Comment by liuliu** [comment]
please use stable branch. remove ./lib/config.mk file if any, and run ./lib/configure first to give proper information about your platform. the unstable (development) branch only tested on Mac from time to time.
