### ISSUE TITLE
DPM Trained Model yields 0% results

### ISSUE THREAD

**Issue by chiragraman** [liuliu/ccv#69]
Hello,

Firstly, thank you for maintaining this library. 

I've been trying to train my own models on the INRIA dataset with dpmcreate. I let it run for 3 days and tested the detector on an intermediate model (Iteration 5.29) and obtained the result 0.0% using the dpmvldtr. 

One of the issues I notice from the detection textfile is that there seem to be 0 parts. Here is a sample line:

```
Test/pos/crop001501.png -23 0 327 22 5.450809 0
```

Also, I notice multiple detections per image.

Running on the latest version from Github doesn't let me even complete training the model, giving inf values for entropy while initializing parts:

```
- model->label[0]: 1, model->nr_class: 2, model->nr_feature: 1395
components == 1, skipped coordinate-descent to optimize root mixture model
initializing part filters
 - initializing part filters for model 1(1)
 ---- part 1(8) 6x6 at (2,0), entropy: inf
 ---- part 2(8) 6x6 at (2,21), entropy: inf
 ---- part 3(8) 6x6 at (2,22), entropy: inf
 ---- part 4(8) 6x6 at (2,23), entropy: inf
 ---- part 5(8) 6x6 at (2,24), entropy: inf
 ---- part 6(8) 5x7 at (0,0), entropy: inf
 ---- part 7(8) 5x7 at (5,0), entropy: inf
 ---- part 8(8) 6x6 at (2,2), entropy: 2452796448898994.000000
optimizing root filter & part filters with stochastic gradient descent
 - collecting responses from positive examples : 0%Assertion failed: (k >= 0 && k < ccv_max(db->rows, db->cols) + 1), function ccv_distance_transform, file ccv_numeric.c, line 1128.
Abort trap: 6
```

Could you please provide some insight into the issue and possible ways of resolving it?

Thanks,

Best,
Chirag

**Comment by liuliu** [comment]
Since the liblinear implementation changed a lot, probably my implementation of using it is out of date, will investigate and fix that.

**Comment by liuliu** [comment]
Hey, https://github.com/liuliu/ccv/commit/98f8d3e6a8dc2c48ce041f479287759d0970144d introduced a regression in how to handle output from liblinear. I fixed it in stable now.

**Comment by chiragraman** [comment]
Hey, thanks a lot! I shall try it out and see if it works for me :)
