### ISSUE TITLE
Variance calculation may be wrong

### ISSUE THREAD

**Issue by xuwangyin** [liuliu/ccv#79]
In lib/ccv_dpm.c variance is calculated as 
`variance = (fn[i].value - mean) * (fn[i].value - mean);`,
shouldn't it be 
`variance += (fn[i].value - mean) * (fn[i].value - mean);`?
There are two appearances of this kind of calculation in this file.

**Comment by liuliu** [comment]
you are absolutely right! lucky that only computes something print out rather than something useful :+1:
