### ISSUE TITLE
BBF demo example not working

### ISSUE THREAD

**Issue by mmp-schmitt** [liuliu/ccv#80]
I am trying to use your wonderful libcvv library on Mac OS X. I managed to compile the code in the lib and bin directory. Now I am trying my first tests, so I am using your first example in the BBF documentation:

bbfdetect test1.jpg ../samples/face | ./bbfdraw.rb test1.jpg output1.jpg

The first part of the call using bbfdetect seems to produce a correct result. The output is:

 66 76 57 57 -1.290872
 total : 1 in time 16ms

bbfdraw.rb is a ruby script, which uses the previously mentioned result and creates a call to the convert program in
 %x[#{sprintf("convert %s -fill none -stroke green -strokewidth 2 %s%s", ARGV[0], rect, ARGV[1])}]

which in my case is converted to:
convert test1.jpg -fill none -stroke green -strokewidth 2 -draw "rectangle 66,76 123,133" output1.jpg

convert fails with the error message 
Assertion failed: (argc == 3), function main, file convert.c, line 6.

When looking into the code I see in line 6 of convert.c
assert(argc == 3);

So convert will always fail. If I reduce the parameters so argc gets the value 3, e.g., by calling “convert test1.jpg output1.jpg” the program works fine and the image is copied and recompressed, but not modified. I can see no code inside convert.c, which would cut a piece out of the incoming image.

What have I missed? Thank you.

**Comment by liuliu** [comment]
Yea, the convert utility is not the convert.c file in /bin. Thanks for noting this and I will remove convert.c from bin in next release.

The convert utility in that script refers to http://www.imagemagick.org/script/convert.php
