### ISSUE TITLE
Linking problem 

### ISSUE THREAD

**Issue by edmajmp** [liuliu/ccv#86]
Hi,

since I'm using g++ to compile to c++ code, I compile libccv with gcc. It generates an static library. However, I tried to use a similar case of the DPM detector into my code. It compiles correctly but I get some linking problem, such as:

../src/detectors/ofVDetectorDPM.cpp:22: error: undefined reference to 'ccv_matrix_free(void_)'
../src/detectors/ofVDetectorDPM.cpp:24: error: undefined reference to 'ccv_drain_cache()'
../src/detectors/ofVDetectorDPM.cpp:27: error: undefined reference to 'ccv_dpm_mixture_model_free(ccv_dpm_mixture_model_t_)'
../src/detectors/ofVDetectorDPM.cpp:32: error: undefined reference to 'ccv_enable_default_cache()'
../src/detectors/ofVDetectorDPM.cpp:34: error: undefined reference to 'ccv_dpm_read_mixture_model(char const_)'
../src/detectors/ofVDetectorDPM.cpp:44: error: undefined reference to 'ccv_read_impl(void const_, ccv_dense_matrix_t**, int, int, int, int)'
../src/detectors/ofVDetectorDPM.cpp:46: error: undefined reference to 'ccv_dpm_detect_objects(ccv_dense_matrix_t*, ccv_dpm_mixture_model_t**, int, ccv_dpm_param_t)'
../src/detectors/ofVDetectorDPM.cpp:72: error: undefined reference to 'ccv_array_free(ccv_array_t*)'

As usual I'm including the location where is located the static library and I'm also put indicate the library name -lccv. Do you know how can I solve this issue?

I look forward for your advise. Thanks

**Comment by liuliu** [comment]
libccv is a C library, try to do this if you haven't yet:

extern "C" {
#include "ccv.h"
}

let me know if it still doesn't work.

## 

Liu Liu
+1 650 521 3058
http://liuliu.me/
http://facebook.com/liu.ll/

**Comment by edmajmp** [comment]
Hi,

I had already try it without success. However, I did it again and it works. I do not know what I did wrong.

Thanks and great work!!

**Comment by ghost** [comment]
Hi liuliu,
I m working in C and facing the same problem and when i use extern "C"{ #include "ccv.h"
} , 

 gcc strokewidthtransform.c -o swt
strokewidthtransform.c:1:12: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 extern (C) {

my code is here,

extern (C) {
#include "ccv.h"
#include <jpeglib.h>
#include "io/_ccv_io_libjpeg.c"
#include <sys/time.h>
#include <ctype.h>
#define SUCCESS 1
#define FAILURE 0

int* swt(char *bytes, int array_length, int width, int height){
    int *result_array;
    int status = FAILURE;
    ccv_enable_default_cache();
	ccv_dense_matrix_t* image = 0;

	FILE *stream;
	stream = fmemopen(bytes, array_length, "r");
	if(stream != NULL){
        int type = CCV_IO_JPEG_FILE | CCV_IO_GRAY;
        int ctype = (type & 0xF00) ? CCV_8U | ((type & 0xF00) >> 8) : 0;
        _ccv_read_jpeg_fd(stream, &image, ctype);

        if (image != 0)
        {
            ccv_array_t* words = ccv_swt_detect_words(image, ccv_swt_default_params);
            if (words)
            {
                int i;
                int result_idx = 1;
                result_array = (int*)malloc((4 * words->rnum + 1) * sizeof(int));
                result_array[0] = 4 * words->rnum;
                for (i = 0; i < words->rnum; i++)
                {
                    ccv_rect_t* rect = (ccv_rect_t*)ccv_array_get(words, i);
                    result_array[result_idx++] = rect->x;
                    result_array[result_idx++] = rect->y;
                    result_array[result_idx++] = rect->width;
                    result_array[result_idx++] = rect->height;
                }
                ccv_array_free(words);
                status = SUCCESS;
            }
            ccv_matrix_free(image);
        }
        ccv_drain_cache();
	}


    if(status != SUCCESS){
        result_array = (int*)malloc(1 * sizeof(int));
        result_array[0] = 0;
    }
    return result_array;
}
}

the extern c only works for c++ not for c, please help me.
