### ISSUE TITLE
Doc typo: docs/convnet.md 

### ISSUE THREAD

**Issue by salmanulhaq** [liuliu/ccv#87]
I guess you meant _GPU_:

"The **CPU** version of forward pass (from RGB image input to the classification result) takes about 700ms per image. This is achieved with multi-threaded convolutional kernel computation. Decaf ( the **CPU** counter-part of Caffe) reported their forward pass..."

**Comment by liuliu** [comment]
It is CPU. Otherwise 700ms per image is deem too slow.
