### ISSUE TITLE
Linker error on Mac OS X 10.9 

### ISSUE THREAD

**Issue by sapa-denis** [liuliu/ccv#88]
Hi!
I have some errors when added libccv.a into my iOS project.
I used latest stable version of your library and builded static lib with make command. 
I read all issues but no one can help me.

Undefined symbols for architecture i386:
  "ccv_read_impl(void const_, ccv_dense_matrix_t_*, int, int, int, int)", referenced from:

  "ccv_array_free(ccv_array_t*)", referenced from:

  "ccv_matrix_free(void*)", referenced from:

  "ccv_swt_detect_words(ccv_dense_matrix_t*, ccv_swt_param_t)", referenced from:

ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by liuliu** [comment]
For the time being, libccv is intended to be used on iOS by including the source code directly (or create your own static library xcode project);

Using ./configure && make will only generate static library for the host computer.

Personally, I don't like the idea of using *.a directly in a iOS project, and much rather to setup xcworkspace and generate these static libraries as part of building the main project.

Thus, in the future, providing a script (such as using gyp) to generate static library xcode project would be ideal. I have plan to set these up, but not there yet (I want to setup CI for iPhone / Android in http://ci.libccv.org).

**Comment by sapa-denis** [comment]
I think that it would be cool if you create CocoaPods dependencies, as everyone can add your lib as xcodeproj to their own workspace just with one command from terminal.

As for my problem, I created workspace and added your lib as xcodeproj, but errors remain.
