### ISSUE TITLE
clang errors during make

### ISSUE THREAD

**Issue by roseperrone** [liuliu/ccv#89]
I get a series of errors like these when I invoke `make`. There might be a missing link against a clang library. I'm running on Mac OS 10.9. What should I change?

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/5.1/include/emmintrin.h(256): error: expression must have pointer-to-object type

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/5.1/include/emmintrin.h(262): error: identifier "__builtin_ia32_cmpsd" is undefined

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/5.1/include/emmintrin.h(268): error: identifier "__builtin_ia32_cmpsd" is undefined

/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/clang/5.1/include/emmintrin.h(274): error: identifier "__builtin_ia32_cmpsd" is undefined

Error limit reached.
100 errors detected in the compilation of "/tmp/tmpxft_000037da_00000000-6_cwc_convnet.cpp1.ii".
Compilation terminated.
make: **\* [cuda/cwc_convnet.o] Error 4

**Comment by roseperrone** [comment]
I found a solution here: http://www.herikstad.net/2009/05/cuda-and-sse2-intrinsics.html. I'm implementing it now...
Actually, upgrading nvcc now. https://devtalk.nvidia.com/default/topic/539513/nvcc-compile-errors-when-using-sse-intrinsic-functions-with-gcc-as-host-compiler/
Nope, that didn't fix it. This is the relevant StackOverflow post: http://stackoverflow.com/questions/20276112/nsight-eclipse-cuda-opencv/23872846#23872846

**Comment by liuliu** [comment]
Hey, can you provide more details on the version of ccv (git sha256 id?), and your config.mk file?

The nvcc compiled file (cuda/cwc_convnet.cu) shouldn't contain any SSE intrinsics. I speed up the normal convnet implementation (ccv_convnet.c) with SSE intrinsics (and NEON intrinsics).

**Comment by liuliu** [comment]
Alternatively, you can undef HAVE_SSE2 for this particular file, although now I am curious about your setup though. I probably need to acquire similar setup to add as buildslave (seems a problem particular to Mac OSX + CUDA, which I don't have such setup for buildslave).

**Comment by roseperrone** [comment]
That worked. Thanks! My version of ccv is the very latest on the unstable branch (4 days since the last push).
