### ISSUE TITLE
How to create a dylib containing only SWT code

### ISSUE THREAD

**Issue by roseperrone** [liuliu/ccv#91]
I want to use this library to create a Python wrapper (using ctypes) for detecting words in images. How should I compile and link a dynamic library that contains just the code necessary for word detection?

**Comment by liuliu** [comment]
Hey, Github issue tracker is for issues with the library (for example: https://github.com/liuliu/ccv/issues/89), not for Q&A (like this one). Please direct your question to Stackoverflow or libccv's website, such as: http://libccv.org/doc/doc-swt/
