### ISSUE TITLE
"convert" called by bbfdraw.rb

### ISSUE THREAD

**Issue by II-Matto** [liuliu/ccv#92]
I tried the command `./bbfdetect <Your Image contains Faces> ../samples/face | ./bbfdraw.rb <Your Image contains Faces> output.png`, but it said "convert" is not found. So I modified bbfdraw.rb to use `./convert`, but "convert" actually assert `argc == 3` while bbfdraw.rb passed more than 3 arguments which provide necessary information. So how can the face bounding box be correctly marked on the image?

**Comment by liuliu** [comment]
convert means the convert command-line offered by http://www.imagemagick.org/script/convert.php

I thought that I removed the ./convert.c. Will do so in the next release.

**Comment by II-Matto** [comment]
Many thanks for your quick response!
