### ISSUE TITLE
ccv bin/cuda compile error

### ISSUE THREAD

**Issue by soumith** [liuliu/ccv#96]
Hey, I compile ccv without any issues (Ubuntu 14.04 64-bit with CUDA 6.0 SDK).

However, when I try compiling the files bin/cuda to do benchmarking, I get the following errors. I checked the paths, and they look fine, and the files in lib/cuda are getting included properly, so I'm not sure why it's not able to see the static functions.

Any insights? Or can you successfully compile the binaries in bin/cuda without any issues?

```
make[1]: Leaving directory `/home/fatbox/code/convnet-benchmarks/ccv/ccv/lib'
clang cwc-bench.c -o cwc-bench.o -c -O3 -Wall -I"../../lib" -msse2 -D HAVE_LIBPNG -D HAVE_LIBJPEG -D HAVE_FFTW3 -D HAVE_CBLAS -D HAVE_AVCODEC -D HAVE_AVFORMAT -D HAVE_SWSCALE -D HAVE_SSE2 -D HAVE_CUDA
nvcc cwc-bench-runtime.cu -o cwc-bench-runtime.o -c -O3 -I"../../lib" -lineinfo --use_fast_math -arch=sm_30 -D HAVE_LIBPNG -D HAVE_LIBJPEG -D HAVE_FFTW3 -D HAVE_CBLAS -D HAVE_AVCODEC -D HAVE_AVFORMAT -D HAVE_SWSCALE -D HAVE_SSE2 -D HAVE_CUDA
cwc-bench-runtime.cu(18): error: identifier "_cwc_convnet_batch_formation" is undefined

cwc-bench-runtime.cu(111): error: identifier "_cwc_convnet_convolutional_backward_propagate" is undefined

cwc-bench-runtime.cu(119): error: identifier "_cwc_convnet_full_connect_backward_propagate" is undefined

cwc-bench-runtime.cu(123): error: identifier "_cwc_convnet_rnorm_backward_propagate" is undefined

cwc-bench-runtime.cu(127): error: identifier "_cwc_convnet_max_pool_backward_propagate" is undefined

cwc-bench-runtime.cu(131): error: identifier "_cwc_convnet_average_pool_backward_propagate" is undefined

6 errors detected in the compilation of "/tmp/tmpxft_00002dd2_00000000-6_cwc-bench-runtime.cpp1.ii".
make: *** [cwc-bench-runtime.o] Error 2
```

**Comment by liuliu** [comment]
Can you include the branch / git hash for the revision you worked on?

Also, can you show the whole command you run? (include the path etc.)

I normally run make from ./bin/cuda without problems.

**Comment by soumith** [comment]
This is the last git log in the branch I worked with (checked out of github just now).

```
commit 043b0810ac5233754b3acce42e24a4ab7cc0c50c
Author: Liu Liu <i@liuliu.me>
Date:   Thu Jul 10 02:08:25 2014 -0400

    added wnid file
```

These are the exact commands I used:
https://github.com/soumith/convnet-benchmarks/blob/master/ccv/README.md

**Comment by liuliu** [comment]
Can you provide the ./lib/config.mk file in ccv directory? That would be helpful for me to replicate your environment. Also, is the code all available on your repo or will there be some extra files?

**Comment by soumith** [comment]
Here is the config.mk https://gist.github.com/e77242509b4bac5c49f8
Thanks for looking into this.

> Also, is the code all available on your repo or will there be some extra files?

The goal of repo is to be self-sufficient, all the code/instructions would be included to reproduce benchmarks. I just started it this weekend and got through caffe, torch (and waiting on some compile errors on nnforge, cxxnet), but on my way to cover all the popular convnet libraries.

**Comment by liuliu** [comment]
Hey, @soumith you need gsl library to compile the training part of the app (search for HAVE_GSL in that file).
  sudo apt-get install libgsl0-dev
should fix this for you.

**Comment by liuliu** [comment]
Also, excited to see some comparison from you!

**Comment by soumith** [comment]
Thanks a lot!!!
