### ISSUE TITLE
repo has huge git files, needs cleaning

### ISSUE THREAD

**Issue by alexandermerritt** [liuliu/ccv#99]
Fresh clone is 1.3GB is in size!

Culprit, at 999MB:
ccv.git/.git/objects/pack/pack-aaa75780a25a9ccc6f6611e9fb4acd9a5ba7f2ad.pack

All other files are reasonable in size - can this be cleaned in some way?

Checking it out, "git gc" didn't seem to remove it.

**Comment by liuliu** [comment]
Thanks. I will remove the imagenet.sqlite3 files from history and recommit these to avoid ever bigger size of these.

**Comment by liuliu** [comment]
cleaned up all image-net.sqlite3 files so no history left.
